# Generated by Django 4.1.5 on 2023-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
